name: Security Scanning

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: go/bridgecrew-action@master
      with:
        api-key: ${{ secrets.BRIDGECREW_API_KEY }}
